using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace hrms_query.Enums
{
    public enum Nationality
    {
        Filipino,
        American,
        British,
        Australian,
        Canadian,
        Chinese,
        Japanese,
        Korean,
        Indian,
        Mexican,
        German,
        French,
        Italian,
        Spanish,
        Russian,
        Brazilian,
        SouthAfrican,
        Thai,
        Vietnamese,
        Malaysian,
        Indonesian,
        Singaporean,
        Pakistani,
        Bangladeshi,
        SaudiArabian,
        Egyptian,
        Turkish,
        Argentinian,
        Colombian,
        Chilean,
        Dutch,
        Swedish,
        Norwegian,
        Finnish,
        Danish,
        Polish,
        Ukrainian,
        Greek,
        Swiss,
        Portuguese,
        NewZealander,
        Iranian,
        Israeli,
        Peruvian,
        Venezuelan,
        Cuban,
        Hungarian,
        Belgian,
        Austrian,
        Irish,
        Emirati,
        Qatari,
        Kuwaiti,
        Nigerian,
        Kenyan,
        Ethiopian,
        Moroccan,
        Algerian,
        Tunisian,
        Burmese,
        Nepalese,
        SriLankan,
        Other
    }

}
